# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "stories", :force => true do |t|
    t.column "name",        :string
    t.column "link",        :string
    t.column "permalink",   :string
    t.column "user_id",     :integer
    t.column "votes_count", :integer,  :default => 0
    t.column "created_at",  :datetime
    t.column "description", :text
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",    :string
    t.column "password", :string
    t.column "name",     :string
    t.column "email",    :string
  end

  create_table "votes", :force => true do |t|
    t.column "story_id",   :integer
    t.column "created_at", :datetime
    t.column "user_id",    :integer
  end

end
